### ISSUE TITLE
ShouldHaveTime_create_Test test fails

### ISSUE THREAD

**Issue by ash2k** [alexruiz/fest-assert-2.x#85]
Failing test:

``` java
  public static final DateFormat ISO_DATE_TIME_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

  @Test
  public void should_create_error_message() throws ParseException {
    Date date = ISO_DATE_TIME_FORMAT.parse("2011-01-01T05:01:00");
    String message = shouldHaveTime(date, Long.MAX_VALUE).create(new TextDescription("Test"));
    assertEquals("[Test] expected <2011-01-01T05:01:00> to have time:\n<9223372036854775807L>\n but was:\n<1293854460000L>",
        message);
  }
```

```
-------------------------------------------------------------------------------
Test set: org.fest.assertions.error.ShouldHaveTime_create_Test
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec <<< FAILURE!
should_create_error_message(org.fest.assertions.error.ShouldHaveTime_create_Test)  Time elapsed: 0.027 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<...7L>
 but was:
<12938[544]60000L>> but was:<...7L>
 but was:
<12938[400]60000L>>
        at junit.framework.Assert.assertEquals(Assert.java:85)
        at junit.framework.Assert.assertEquals(Assert.java:91)
        at org.fest.assertions.error.ShouldHaveTime_create_Test.should_create_error_message(ShouldHaveTime_create_Test.java:43)
```

I guess the test is failing because the time zone is not specified here and my time zone is different from the zone of the test's author.

**Comment by joel-costigliola** [comment]
You are right, I'll fix this right away.
Thanks for reporting this.
