### ISSUE TITLE
BinaryDiff_diff_File_byteArray_Test test fails

### ISSUE THREAD

**Issue by helvalius** [alexruiz/fest-assert-2.x#92]
Hi,
I just forked the repository and did a "mvn clean install". The following two test cases in the class "BinaryDiff_diff_File_byteArray_Test" failed  (on two computers). Test setup is Windows 7 x64 with Java Version 1.7 and on the other Windows 7 x64 with Java 1.6. 

Failing Test:

``` Java
  @Test
  public void should_return_no_diff_if_file_and_array_have_equal_content() throws IOException {
    writer.write(actual, "test");
    // Note: writer inserts a \n after each line so we need it in our expected content
    expected = "test\n".getBytes();
    BinaryDiffResult result = binaryDiff.diff(actual, expected);
    assertTrue(result.hasNoDiff());
  }

```

``` Java
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:92)
    at org.junit.Assert.assertTrue(Assert.java:43)
    at org.junit.Assert.assertTrue(Assert.java:54)
    at  org.fest.assertions.internal.files.BinaryDiff_diff_File_byteArray_Test.should_return_no_diff_if_file_and_array_have_equal_content(BinaryDiff_diff_File_byteArray_Test.java:65)
```

and the second one  in the same class is

``` Java
  @Test
  public void should_return_diff_if_actual_is_shorter() throws IOException {
    writer.write(actual, "foo");
    expected = "foo\nbar".getBytes();
    BinaryDiffResult result = binaryDiff.diff(actual, expected);
    assertEquals(4, result.offset);
    assertEquals("EOF", result.actual);
    assertEquals("0x62", result.expected);
  }
```

``` Java
junit.framework.AssertionFailedError: expected:<4> but was:<3>
    at junit.framework.Assert.fail(Assert.java:50)
    at junit.framework.Assert.failNotEquals(Assert.java:287)
    at junit.framework.Assert.assertEquals(Assert.java:67)
    at junit.framework.Assert.assertEquals(Assert.java:199)
    at junit.framework.Assert.assertEquals(Assert.java:205)
    at org.fest.assertions.internal.files.BinaryDiff_diff_File_byteArray_Test.should_return_diff_if_actual_is_shorter(BinaryDiff_diff_File_byteArray_Test.java:83)

```

The test file for the second test case is:

```
foo
```

Could it be that it differs in the binary due to a different encoding on Windows?

**Comment by joel-costigliola** [comment]
Hi,

Everything works fine ... on linux at least !

I'm suspecting that \n usage to cause the problem, I have replaced them by `System.getProperty("line.separator")`.
Can you tell me if it fixes the problem ?

Thanks for reporting this !

Joel

**Comment by helvalius** [comment]
Hi,

I needed to change the expected size of the result on the second above test case, I changed

``` Java
  @Test
  public void should_return_diff_if_actual_is_shorter() throws IOException {
    writer.write(actual, "foo");
    expected = "foo\nbar".getBytes();
    BinaryDiffResult result = binaryDiff.diff(actual, expected);
    assertEquals(4, result.offset);
    assertEquals("EOF", result.actual);
    assertEquals("0x62", result.expected);
  }
```

into

``` Java
  @Test
  public void should_return_diff_if_actual_is_shorter() throws IOException {
    writer.write(actual, "foo");
    expected = ("foo"+LINE_SEPARATOR+"bar").getBytes();
    BinaryDiffResult result = binaryDiff.diff(actual, expected);
    assertEquals(3+LINE_SEPARATOR.length(), result.offset);
    assertEquals("EOF", result.actual);
    assertEquals("0x62", result.expected);
  }
```

with this change it  works. The line separators are two characters on windows and thus the expectation  was at least incorrect on windows.  It should be more flexible with the new code. 

Jan

Edit:  org.fest.util.Systems.LINE_SEPARATOR is a constant in the utils library that wraps the system property.

**Comment by joel-costigliola** [comment]
You are obviously right ...
I have pushed your fix, hope it solves this issue definitely.

**Comment by helvalius** [comment]
It works now with your latest commit and can be closed :).

**Comment by joel-costigliola** [comment]
cool :)
Thanks again !
